[tool.poetry]
name = "boomer-test"
version = "0.1.0"
description = ""
authors = ["Evan <suzukaze.hazuki2020@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

